server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ok
mybatis:
  mapper-locations: classpath:mapper/*.xml
